package dbp.connect.Excepciones;

public class RecursoNoEncontradoException extends RuntimeException {

    public RecursoNoEncontradoException(String message){
        super(message);

    }
}
